# Generated by Django 5.2.1 on 2025-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('times_watched', models.IntegerField(default=1)),
                ('first_watched_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('previously_watched_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
